name: Deploy To Github Pages

on:
  push:
    branches: ["main", "fix/ci", "chore/ci-cache"]

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Nix Develop
      uses: nicknovitski/nix-develop@v1

    - name: Cache dependencies
      uses: useblacksmith/cache@v5
    - name: Setup rust cache
      uses: useblacksmith/rust-cache@v3

    - name: Build nu wasm
      run: make prod
    - name: Install bun dependencies
      run: bun install --frozen-lockfile
      working-directory: playground
    - name: Build playground
      run: bun run build
      working-directory: playground

    - name: Create gh-pages worktree
      run: git worktree add --checkout gh-pages
    - name: Clear gh-pages worktree
      run: rm -rf gh-pages/*
    - name: Copy build result to gh-pages worktree
      run: cp -r playground/dist/. gh-pages/
    - uses: EndBug/add-and-commit@v9
      with:
        cwd: gh-pages
        push: origin gh-pages --force

