name: Deploy To Github Pages

on:
  push:
    branches: ["main", "feat/cd"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: |
          cwd: playground
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - name: build nu wasm
      run: wasm-pack build --target web --out-dir playground/src/wasm
    - name: Build playground
      run: pnpm build
      working-directory: playground
    - name: Create gh-pages worktree
      run: git worktree add --checkout gh-pages
    - name: Clear gh-pages worktree
      run: rm -rf gh-pages/*
    - name: Copy build result to gh-pages worktree
      run: cp -r playground/dist/. gh-pages/
    - uses: EndBug/add-and-commit@v9
      with:
        cwd: gh-pages
        push: origin gh-pages --force

