name: Deploy To Github Pages

on:
  push:
    branches: ["main", "fix/ci"]

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v2
    - name: Install Bun Dependencies
      run: bun install --frozen-lockfile
      working-directory: playground
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - name: build nu wasm
      run: wasm-pack build --target web --no-pack --release --out-dir playground/src/wasm
    - name: Build playground
      run: bun run build
      working-directory: playground
    - name: Create gh-pages worktree
      run: git worktree add --checkout gh-pages
    - name: Clear gh-pages worktree
      run: rm -rf gh-pages/*
    - name: Copy build result to gh-pages worktree
      run: cp -r playground/dist/. gh-pages/
    - uses: EndBug/add-and-commit@v9
      with:
        cwd: gh-pages
        push: origin gh-pages --force

